apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: my-first-release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-first-release-name-nginx-ingress
    helm.sh/chart: nginx-ingress-0.3.3
  name: my-first-release-name-nginx-ingress
  namespace: my-first-namespace
