apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: my-first-release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-first-release-name-nginx-ingress
    helm.sh/chart: nginx-ingress-0.3.3
  name: my-controller
  namespace: my-first-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: '9113'
        prometheus.io/scrape: 'true'
      labels:
        app: my-controller
    spec:
      containers:
        - args:
            - -nginx-plus=false
            - -nginx-configmaps=$(POD_NAMESPACE)/my-first-release-name-nginx-ingress
            - -default-server-tls-secret=$(POD_NAMESPACE)/my-first-release-name-nginx-ingress-default-server-secret
            - -ingress-class=nginx
            - -use-ingress-class-only=false
            - -health-status=false
            - -nginx-debug=false
            - -nginx-status=true
            - -nginx-status-port=8080
            - -nginx-status-allow-cidrs=127.0.0.1
            - -report-ingress-status
            - -external-service=my-first-release-name-nginx-ingress
            - -enable-leader-election=true
            - -leader-election-lock-name=my-first-release-name-nginx-ingress-leader-election
            - -enable-prometheus-metrics=true
            - -prometheus-metrics-listen-port=9113
            - -enable-custom-resources=false
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: custom_repo:1.5.3
          imagePullPolicy: IfNotPresent
          name: my-first-release-name-nginx-ingress
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 9113
              name: prometheus
      hostNetwork: false
      serviceAccountName: my-first-release-name-nginx-ingress
