apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: my-first-release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-first-release-name-nginx-ingress
    helm.sh/chart: nginx-ingress-0.3.3
  name: my-first-release-name-nginx-ingress
rules:
  - apiGroups:
      - ''
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - update
      - create
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: my-first-release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-first-release-name-nginx-ingress
    helm.sh/chart: nginx-ingress-0.3.3
  name: my-first-release-name-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-first-release-name-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: my-first-release-name-nginx-ingress
    namespace: my-first-namespace
